### ISSUE TITLE
g

### ISSUE THREAD

**Issue by willnode-tkpd** [willnode/ci4-admin-lte#3]
https://google.com

**Comment by willnode** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.provision/com.android.provision.global.GlobalDefaultActivity}: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.miui.cloudservice/com.miui.cloudservice.ui.CloudServiceSettingsActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.miui.cloudservice/com.miui.cloudservice.ui.CloudServiceSettingsActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2020)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1679)
	at android.app.Activity.startActivityForResult(Activity.java:4651)
	at android.app.Activity.startActivityForResult(Activity.java:4609)
	at com.android.provision.global.GlobalDefaultActivity$State.onEnter(GlobalDefaultActivity.java:170)
	at com.android.provision.global.GlobalDefaultActivity$StateMachine.start(GlobalDefaultActivity.java:472)
	at com.android.provision.global.GlobalDefaultActivity.onCreate(GlobalDefaultActivity.java:61)
	at android.app.Activity.performCreate(Activity.java:7224)
	at android.app.Activity.performCreate(Activity.java:7213)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
	... 11 more
